### ISSUE TITLE
New branch titled branch1

### ISSUE THREAD

**Issue by jamboee** [YixinZhang92/RadPattern101#1]
Guys,
I created a new branch titled "branc1". it contains many files including the ones that contains the prototypes and the Makefile. Take a look at it. If you think it's good, we can continues using this one instead of master branch. @oluwaseunfadugba  and @YixinZhang92

**Comment by oluwaseunfadugba** [comment]
Hey Eric,
Thanks for the good job. If we all decided, we could merge this branch with the master because, for some reasons, the master sounds right to me.

Cheers bro

**Comment by jamboee** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Yeah sure. If we feel ok with it, we can merge it with master. I didn't want to merge them before if we all agree on it and after we all see the difference between the two branches.


Sent from Yahoo Mail for iPhone


On Sunday, February 26, 2017, 6:39 PM, oluwaseunfadugba <notifications@github.com> wrote:


Hey Eric,
Thanks for the good job. If we all decided, we could merge this branch with the master because, for some reasons, the master sounds right to me.

Cheers bro

**Comment by oluwaseunfadugba** [comment]
The only thing is that Yixin read_in code is not included. I will work on the indentation and the comments.

**Comment by YixinZhang92** [comment]
please wait, I am working on functions. Or I can do the identation after I upload the new readin file.

**Comment by jamboee** [comment]
Guys, I just modified Yixin's read_in function to make it shorter. The issues with this function is that it's not printing anything on the screen and the values are not treated as numbers. Therefore, you can't check id they are negative or not. @oluwaseunfadugba @YixinZhang92

**Comment by YixinZhang92** [comment]
yes, that's why I am still working on it.

**Comment by jamboee** [comment]
@YixinZhang92 
I can copy the modified code here and then you can check it. I didn't change anything really. Maybe that can help with what you are working on.

**Comment by jamboee** [comment]
@YixinZhang92 
check the branch titled "branch1". I divided the file mainfile_test.cpp located on master branch in three files: main.cpp, prototypes.cpp, and prototypes.h. These three files are now located on branch called branch1. ON this branch called branch1 there is a new Makefile that works with the new three files created. we wanted to merge master branch and branch1 and we keep working on master branch with the new files.

**Comment by YixinZhang92** [comment]
Great, so what should I do for this? sorry....still confused about what I need to do for the changes and merging things.

By the way, I uploaded the new read in file.

**Comment by YixinZhang92** [comment]
oh, I guess you are asking me what should be changed for the readin file when you merging two branches.

I should say you can just delete the readin file in branch1, and when merging these two branches, leave the readin file of the master branch as what it was.

**Comment by oluwaseunfadugba** [comment]
Thanks Yixin. I will continue to work on Doxygen. Hopefully it won't change anything. Yixin and Eric, please are you working on the master branch or the branch1?

 

    On Monday, February 27, 2017 1:38 PM, YixinZhang92 <notifications@github.com> wrote:
 

 yes, that's why I am still working on it.—

**Comment by YixinZhang92** [comment]
I uploaded the new read_test.cpp to the master branch.

**Comment by oluwaseunfadugba** [comment]
Thanks Yixin. I think we should make the master branch our platform. We can test our ideas on new branch(es) but merge or copy the changes, when we are okay with the new development, on the master so that we can all be on the same page. Thanks! Cheers 

    On Monday, February 27, 2017 1:34 PM, YixinZhang92 <notifications@github.com> wrote:
 

 I uploaded the new read_test.cpp to the master branch.—

**Comment by jamboee** [comment]
we keep both branches. master branch contain the usable files for the project and the other branch contains the testing files.

**Comment by YixinZhang92** [comment]
OK, then I will upload the same new readin file to the test branch right now.

**Comment by jamboee** [comment]
Since Ricardo will test what we have by tomorrow, we need to clean up the master branch. we get rid of mainfile_test.cpp and the Makefile or we can move them to the test branch.Then we upload main.cpp, prototypes.cpp, prototypes.h and the corresponding Makefile from testbranch to the master branch. what do u think?

**Comment by jamboee** [comment]
is there any way to combine the variable_names that have strings as variable_values in one if statement and combine the variable_names that have floats as variable_values in one another if statement? @ @YixinZhang92 . This way it will be easier to use another one if statement that checks the validity of the parameters (negative sign mostly). @oluwaseunfadugba

**Comment by YixinZhang92** [comment]
I think we need to keep the master as a whole one which can be operated by tomorrow. For branch1, can we just keep it as a test platform, we don't need to let Ricardo see this branch, branch1.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jamboee** [comment]
if we keep master as it is right now, it will contain files we don't need i.e mainfile_test.cpp and Makefile. I agree, we keep branch1 as a test platform. But we need to upload the 4 files i kept mentioning above from branch1 to master branch because they show the progress and the show that we finished the task given on Thursday.

**Comment by YixinZhang92** [comment]
Hi Eric, I just changed the main file so that if you run the main file you can get the results. I also find out that you helped me add some checking types functions. Thanks, and I will go on editing them to fit our project.

Sorry for not understanding your messages, Seun called me and explained to me. Thanks, Eric.

**Comment by jamboee** [comment]
@YixinZhang92 

I have three requests:
1st: 
is there any way to combine the variable_names that have strings as variable_values in one IF statement and combine the variable_names that have floats as variable_values in one another IF statement? 
2nd: 
How to check the validity of the parameters (negative values).
3rd:
Since we are now using main.cpp as the main file not mainfile_test.cpp. so, Can you modify read_test.cpp in order to be run using only command line "make"?? That means some parts will go in prototypes.cpp, others in prototypes.h, others in main.cpp and we will have to modify Makefile. Let us know if there is any confusion or any other question.

**Comment by YixinZhang92** [comment]
1. The type of viable values are defined by us, not the input file itself. So, we can only make it to string or to float by our own chosen.

2. Yes, I can do that, I will try to add some checking functions.

3. Yes, I just saw you did a great job on main.cpp. Sorry, I was still stuck in the main_test and only changed the main_test. However, I will try to get the readin file became prototypes and make it to fit the main.cpp.

Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by YixinZhang92** [comment]
Hey guys, I uploaded changes for main.cpp, prototypes.cpp, and prototypes.h. 

I have made documentations to mark those parts were just testing and modified by me.

The files compiled successfully, but the problem is that it was not running. 

Other parts of the main program can run well. They can return "Running...", but the read_in part that I uploaded does not work. It does not return anything.

Hope to see you soon.

**Comment by jamboee** [comment]
When I ran command "make" in the Terminal, I got errors coming from main.cpp and I don't even know hot to correct them. So, I didn't get any results which means if they are not corrected by the time of class, Ricardo will get the same errors as well.

**Comment by YixinZhang92** [comment]
Sorry, I see what's going on. I will correct it as soon as I can.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by YixinZhang92** [comment]
I correct some of them, and I didn't change anything of the original part. However, there are some new errors coming out from the original part. I don't know how to deal with them.
