### ISSUE TITLE
Documentation for Doxygen is completed!

### ISSUE THREAD

**Issue by oluwaseunfadugba** [YixinZhang92/RadPattern101#2]
Hello guys,
I just wanted to let you know that the documentation for Doxygen is competed. Please let us maintain the indentation. I have also deleted the read_test.cpp to avoid confusion. @YixinZhang92, please let me know if you need it back.
Thank you so much. Happy Spring Break!
Oluwaseun

**Comment by YixinZhang92** [comment]
Thanks, Seun. I don't need it, thank you for deleting it. I have corrected files so that the program can compile and run.

I will check the indentation. Thanks for your great job!


Cheers,
Yixin

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
